Rails.application.routes.draw do
  get 'work_rooms/new'
  get 'work_rooms/show'
  get 'work_rooms/edit'
  get 'work_rooms/update'
  get 'work_rooms/destroy'
  get 'work_rooms/index'
  get 'work_rooms/index_new'
  get 'work_rooms/index_reccomend'
  get 'work_rooms/search'
  get 'creator_items/show'
  get 'save_items/create'
  get 'save_items/destroy'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'comments/create'
  get 'comments/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
  get 'users/show'
  get 'homes/top'
  get 'homes/about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
